export const PICKUP_REQUEST_LIST_REQUEST = "PICKUP_REQUEST_LIST_REQUEST";
export const PICKUP_REQUEST_LIST_SUCCESS = "PICKUP_REQUEST_LIST_SUCCESS";
export const PICKUP_REQUEST_LIST_FAIL = "PICKUP_REQUEST_LIST_FAIL";

export const PICKUP_REQUEST_CREATE_REQUEST = "PICKUP_REQUEST_CREATE_REQUEST";
export const PICKUP_REQUEST_CREATE_SUCCESS = "PICKUP_REQUEST_CREATE_SUCCESS";
export const PICKUP_REQUEST_CREATE_FAIL = "PICKUP_REQUEST_CREATE_FAIL";

export const PICKUP_REQUEST_UPDATE_REQUEST = "PICKUP_REQUEST_UPDATE_REQUEST";
export const PICKUP_REQUEST_UPDATE_SUCCESS = "PICKUP_REQUEST_UPDATE_SUCCESS";
export const PICKUP_REQUEST_UPDATE_FAIL = "PICKUP_REQUEST_UPDATE_FAIL";

export const PICKUP_REQUEST_DELETE_REQUEST = "PICKUP_REQUEST_DELETE_REQUEST";
export const PICKUP_REQUEST_DELETE_SUCCESS = "PICKUP_REQUEST_DELETE_SUCCESS";
export const PICKUP_REQUEST_DELETE_FAIL = "PICKUP_REQUEST_DELETE_FAIL";
