apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
  volumes:
    - name: mongodb-storage
      persistentVolumeClaim:
        claimName: mongodb-pvc
