apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: mongo-disk
    diskURI: <disk-uri>
    cachingMode: None
  storageClassName: managed-premium
