name: Deploy MERN app to AKS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy MERN app
        run: make -f kubernetes/Makefile deploy
      - name: Verify deployment
        run: |
          kubectl get pods -n my-app
          kubectl get services -n my-app
